version: '3.8'

services:
  db:
    image: postgres:15
    container_name: echo_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: echo_api
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./echo-api/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
