// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: proto/upload/file.proto

package upload

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FileUploadClient is the client API for FileUpload service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileUploadClient interface {
	// UploadFile uploads a file and returns metadata
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (FileUpload_UploadFileClient, error)
	// GetFileMetadata returns metadata for a specific file
	GetFileMetadata(ctx context.Context, in *GetFileMetadataRequest, opts ...grpc.CallOption) (*FileMetadata, error)
}

type fileUploadClient struct {
	cc grpc.ClientConnInterface
}

func NewFileUploadClient(cc grpc.ClientConnInterface) FileUploadClient {
	return &fileUploadClient{cc}
}

func (c *fileUploadClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (FileUpload_UploadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &FileUpload_ServiceDesc.Streams[0], "/fileupload.FileUpload/UploadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &fileUploadUploadFileClient{stream}
	return x, nil
}

type FileUpload_UploadFileClient interface {
	Send(*UploadFileRequest) error
	CloseAndRecv() (*UploadFileResponse, error)
	grpc.ClientStream
}

type fileUploadUploadFileClient struct {
	grpc.ClientStream
}

func (x *fileUploadUploadFileClient) Send(m *UploadFileRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fileUploadUploadFileClient) CloseAndRecv() (*UploadFileResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fileUploadClient) GetFileMetadata(ctx context.Context, in *GetFileMetadataRequest, opts ...grpc.CallOption) (*FileMetadata, error) {
	out := new(FileMetadata)
	err := c.cc.Invoke(ctx, "/fileupload.FileUpload/GetFileMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileUploadServer is the server API for FileUpload service.
// All implementations must embed UnimplementedFileUploadServer
// for forward compatibility
type FileUploadServer interface {
	// UploadFile uploads a file and returns metadata
	UploadFile(FileUpload_UploadFileServer) error
	// GetFileMetadata returns metadata for a specific file
	GetFileMetadata(context.Context, *GetFileMetadataRequest) (*FileMetadata, error)
	mustEmbedUnimplementedFileUploadServer()
}

// UnimplementedFileUploadServer must be embedded to have forward compatible implementations.
type UnimplementedFileUploadServer struct {
}

func (UnimplementedFileUploadServer) UploadFile(FileUpload_UploadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedFileUploadServer) GetFileMetadata(context.Context, *GetFileMetadataRequest) (*FileMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileMetadata not implemented")
}
func (UnimplementedFileUploadServer) mustEmbedUnimplementedFileUploadServer() {}

// UnsafeFileUploadServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileUploadServer will
// result in compilation errors.
type UnsafeFileUploadServer interface {
	mustEmbedUnimplementedFileUploadServer()
}

func RegisterFileUploadServer(s grpc.ServiceRegistrar, srv FileUploadServer) {
	s.RegisterService(&FileUpload_ServiceDesc, srv)
}

func _FileUpload_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileUploadServer).UploadFile(&fileUploadUploadFileServer{stream})
}

type FileUpload_UploadFileServer interface {
	SendAndClose(*UploadFileResponse) error
	Recv() (*UploadFileRequest, error)
	grpc.ServerStream
}

type fileUploadUploadFileServer struct {
	grpc.ServerStream
}

func (x *fileUploadUploadFileServer) SendAndClose(m *UploadFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fileUploadUploadFileServer) Recv() (*UploadFileRequest, error) {
	m := new(UploadFileRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _FileUpload_GetFileMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileUploadServer).GetFileMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fileupload.FileUpload/GetFileMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileUploadServer).GetFileMetadata(ctx, req.(*GetFileMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileUpload_ServiceDesc is the grpc.ServiceDesc for FileUpload service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileUpload_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fileupload.FileUpload",
	HandlerType: (*FileUploadServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFileMetadata",
			Handler:    _FileUpload_GetFileMetadata_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFile",
			Handler:       _FileUpload_UploadFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/upload/file.proto",
}
