version: '3.8'

services:
  upload-service:
    build:
      context: ./upload-service
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_URL=postgres://postgres:password@host.docker.internal:5432/echo_api?sslmode=disable
    extra_hosts:
      - "host.docker.internal:host-gateway"

  download-service:
    build:
      context: ./download-service
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_URL=postgres://postgres:password@host.docker.internal:5432/echo_api?sslmode=disable
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  pgdata: 